### ISSUE TITLE
Question about received invalid webhook response

### ISSUE THREAD

**Issue by jimmyraywv** [douglasmakey/admissioncontroller#4]
Kubernetes 1.24

I am trying to use your example. I keep getting this kubectl response when I try to create a pod:
```
Error from server (InternalError): error when creating "k8s/2-test-pod.yaml": Internal error occurred: failed calling webhook "pods.notary-admission.aws.com": received invalid webhook response: expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
```

The logs show that this is the JSON being sent back, via `w.Write(res)`.

```
{
    "response": {
        "uid": "b49776cd-5398-4082-974d-9f4943875914",
        "allowed": false,
        "status": {
            "metadata": {},
            "message": "Your pod has the wrong name"
        }
    }
}
```

```
{
    "response": {
        "uid": "a6761f60-3c79-4943-9a03-732e274baddc",
        "allowed": true,
        "status": {
            "metadata": {}
        }
    }
}
```

The webhook config is:
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: notary-admission
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0t...==
    service:
      name: notary-admission
      namespace: notary-admission
      path: /validate/pods
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: pods.notary-admission.aws.com
  namespaceSelector:
    matchExpressions:
    - key: notary-admission-ignore
      operator: NotIn
      values:
      - ignore
  objectSelector: {}
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
```

Both `allowed=true` and `allowed=false` conditions elicit the same response from the webhook. Any chance you have seen this error before? I changed to `"k8s.io/api/admission/v1"` from `"k8s.io/api/admission/v1beta1"` in hopes that it would fix the issue, but it didn't.
